In [1]:
import pandas as pd
import numpy as np

In [2]:
answers = pd.read_csv('answers.csv')
#answer_scores = pd.read_csv('answer_scores.csv')
#comments = pd.read_csv('comments.csv')
emails = pd.read_csv('emails.csv')
#groups = pd.read_csv( 'groups.csv')
#group_memberships = pd.read_csv( 'group_memberships.csv')
#matches = pd.read_csv('matches.csv')
professionals = pd.read_csv('professionals.csv')
questions = pd.read_csv('questions.csv')
#question_scores = pd.read_csv('question_scores.csv')
#school_memberships = pd.read_csv('school_memberships.csv')
#students = pd.read_csv('students.csv')
tags = pd.read_csv('tags.csv')
tag_questions = pd.read_csv('tag_questions.csv')
tag_users = pd.read_csv('tag_users.csv')

In [90]:
questions.head()

,questions_id,questions_author_id,questions_date_added,questions_title,questions_body,questions_full_text
0,332a511f1569444485cf7a7a556a5e54,8f6f374ffd834d258ab69d376dd998f5,2016-04-26 11:14:26,Teacher career question,What is a maths teacher? what is a ma...,Teacher career question What is a ma...
1,eb80205482e4424cad8f16bc25aa2d9c,acccbda28edd4362ab03fb8b6fd2d67b,2016-05-20 16:48:25,I want to become an army officer. What can I d...,I am Priyanka from Bangalore . Now am in 10th ...,I want to become an army officer What can I d...
2,4ec31632938a40b98909416bdd0decff,f2c179a563024ccc927399ce529094b5,2017-02-08 19:13:38,Will going abroad for your first job increase ...,I'm planning on going abroad for my first job....,Will going abroad for your first job increase ...
3,2f6a9a99d9b24e5baa50d40d0ba50a75,2c30ffba444e40eabb4583b55233a5a4,2017-09-01 14:05:32,To become a specialist in business management...,i hear business management is a hard way to ge...,To become a specialist in business management...
4,5af8880460c141dbb02971a1a8369529,aa9eb1a2ab184ebbb00dc01ab663428a,2017-09-01 02:36:54,Are there any scholarships out there for stude...,I'm trying to find scholarships for first year...,Are there any scholarships out there for stude...

## 날짜를 모두 일정하게 타입 변환

In [4]:
answers['answers_date_added'] = pd.to_datetime(answers['answers_date_added'], infer_datetime_format=True)
comments['comments_date_added'] = pd.to_datetime(comments['comments_date_added'], infer_datetime_format=True)
emails['emails_date_sent'] = pd.to_datetime(emails['emails_date_sent'], infer_datetime_format=True)
professionals['professionals_date_joined'] = pd.to_datetime(professionals['professionals_date_joined'], infer_datetime_format=True)
questions['questions_date_added'] = pd.to_datetime(questions['questions_date_added'], infer_datetime_format=True)
students['students_date_joined'] = pd.to_datetime(students['students_date_joined'], infer_datetime_format=True)

In [5]:
questions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23931 entries, 0 to 23930
Data columns (total 5 columns):
questions_id            23931 non-null object
questions_author_id     23931 non-null object
questions_date_added    23931 non-null datetime64[ns]
questions_title         23931 non-null object
questions_body          23931 non-null object
dtypes: datetime64[ns](1), object(4)
memory usage: 934.9+ KB

In [91]:
questions[questions['questions_id']=='6725b02443e44b3e8dca5fcf842f74ec']

,questions_id,questions_author_id,questions_date_added,questions_title,questions_body,questions_full_text
3878,6725b02443e44b3e8dca5fcf842f74ec,2a12b83aee8745f59adc332991405e9f,2019-01-17 22:24:27,I am studying propulsion and thinking to chang...,#licenceengineer #aerospace #aircraftmaintenac...,I am studying propulsion and thinking to chang...

In [7]:
matches.head(10)

   matches_email_id               matches_question_id
0           1721939  332a511f1569444485cf7a7a556a5e54
1           1665388  332a511f1569444485cf7a7a556a5e54
2           1636634  332a511f1569444485cf7a7a556a5e54
3           1635498  332a511f1569444485cf7a7a556a5e54
4           1620298  332a511f1569444485cf7a7a556a5e54
5           1618336  332a511f1569444485cf7a7a556a5e54
6           1610422  332a511f1569444485cf7a7a556a5e54
7           1601694  332a511f1569444485cf7a7a556a5e54
8           1568908  332a511f1569444485cf7a7a556a5e54
9           1551730  332a511f1569444485cf7a7a556a5e54

In [8]:
questions['questions_full_text'] = questions['questions_title'] +'\r\n\r\n'+ questions['questions_body']

In [9]:
questions['questions_full_text']

0        Teacher   career   question\r\n\r\nWhat  is  a...
1        I want to become an army officer. What can I d...
2        Will going abroad for your first job increase ...
3        To become a specialist in business  management...
4        Are there any scholarships out there for stude...
5        How many years of coege do you need to be an e...
6        I want to become a doctor because of my great ...
7        what kind of  college could i go  to for a soc...
8        What are the college classes like for and grap...
9        what does it take to be an anesthesiologist?\r...
10       What major is best for an aspiring Occupationa...
11       How does the gender gap effect productivity in...
12       As a civil engineer, what percent of your time...
13       what is the hardest about becoming a lawyer?\r...
14       How to have a board that can attract $500,000 ...
15       To be a dental hygienist or a dentist?\r\n\r\n...
16       Is it better to sell your invention idea(s) to...
17       Who/what do you think truly decides where you ...
18       How can I get my work in Android development n...
19       Which topics in college most helped with your ...
20       How easy/hard is it to find a job in architect...
21       If medicine improves and allows people to live...
22       Why are there not more females that help or su...
23       What Is The Best Undergraduate Degree Before P...
24       i am searching college for engineering in civi...
25       I am really interested in science, but not so ...
26       How to not give up on college when you are fee...
27       Question for professions at PwC! What is your ...
28       How do I know I will get a job after college?\...
29       Are there any rules of thumb when it comes to ...
                               ...
23901    Given that they are used in a constructive man...
23902    How can I tell my parents that I do not want a...
23903    How would I go about becoming a nurse?\r\n\r\n...
23904    Psycology Compensation\r\n\r\nHow much can neu...
23905    Where is a nice and convenient location for a ...
23906    What was your first job in the game developmen...
23907    Is there a way I can combine my interest in bu...
23908    Is "return offer" the major way of getting a j...
23909    How do you maintain a balance between doing wh...
23910    What specific steps should I be taking to ensu...
23911    What can I do with a communications major?\r\n...
23912    How would you characterize an average day at y...
23913    How do I major and minor\r\n\r\nThe main degre...
23914    Is there a program where you can obtain your M...
23915    Pediatrics\r\n\r\nI'm a junior in high school ...
23916    On average how much do lawyers make a year in ...
23917    What is the best foreign language to learn in ...
23918    How do I become a doctor?\r\n\r\nI'd love to b...
23919    How will I benefit from studying abroad?\r\n\r...
23920    As a nurse, when in your career, and how did y...
23921    Did college help you become a better writer?\r...
23922    Is graduate school a lot harder than regular c...
23923    What should you tell professionals when networ...
23924    What colleges/universities/degrees should I be...
23925    What is success and happiness\r\n\r\nTell me s...
23926    What is a computer engineer & a computer progr...
23927    What major do I need to study to be a writer\r...
23928    Which careers are good if I enjoy working with...
23929    How can going to college help me advance my ca...
23930    Is age a factor for hiring entry level compute...
Name: questions_full_text, Length: 23931, dtype: object

In [10]:
import re

# <br> html 태그는 replace 함수로 공백으로 변환
questions['questions_full_text'] = questions['questions_full_text'].str.replace('<br />',' ')

# 파이썬의 정규 표현식 모듈인 re를 이용하여 영어 문자열이 아닌 문자는 모두 공백으로 변환 
questions['questions_full_text'] = questions['questions_full_text'].apply( lambda x : re.sub("[^a-zA-Z]", " ", x) )

In [11]:
questions['questions_full_text']

0        Teacher   career   question    What  is  a  ma...
1        I want to become an army officer  What can I d...
2        Will going abroad for your first job increase ...
3        To become a specialist in business  management...
4        Are there any scholarships out there for stude...
5        How many years of coege do you need to be an e...
6        I want to become a doctor because of my great ...
7        what kind of  college could i go  to for a soc...
8        What are the college classes like for and grap...
9        what does it take to be an anesthesiologist   ...
10       What major is best for an aspiring Occupationa...
11       How does the gender gap effect productivity in...
12       As a civil engineer  what percent of your time...
13       what is the hardest about becoming a lawyer   ...
14       How to have a board that can attract          ...
15       To be a dental hygienist or a dentist     I m ...
16       Is it better to sell your invention idea s  to...
17       Who what do you think truly decides where you ...
18       How can I get my work in Android development n...
19       Which topics in college most helped with your ...
20       How easy hard is it to find a job in architect...
21       If medicine improves and allows people to live...
22       Why are there not more females that help or su...
23       What Is The Best Undergraduate Degree Before P...
24       i am searching college for engineering in civi...
25       I am really interested in science  but not so ...
26       How to not give up on college when you are fee...
27       Question for professions at PwC  What is your ...
28       How do I know I will get a job after college  ...
29       Are there any rules of thumb when it comes to ...
                               ...
23901    Given that they are used in a constructive man...
23902    How can I tell my parents that I do not want a...
23903    How would I go about becoming a nurse     I am...
23904    Psycology Compensation    How much can neurosc...
23905    Where is a nice and convenient location for a ...
23906    What was your first job in the game developmen...
23907    Is there a way I can combine my interest in bu...
23908    Is  return offer  the major way of getting a j...
23909    How do you maintain a balance between doing wh...
23910    What specific steps should I be taking to ensu...
23911    What can I do with a communications major     ...
23912    How would you characterize an average day at y...
23913    How do I major and minor    The main degree I ...
23914    Is there a program where you can obtain your M...
23915    Pediatrics    I m a junior in high school and ...
23916    On average how much do lawyers make a year in ...
23917    What is the best foreign language to learn in ...
23918    How do I become a doctor     I d love to becom...
23919    How will I benefit from studying abroad     St...
23920    As a nurse  when in your career  and how did y...
23921    Did college help you become a better writer   ...
23922    Is graduate school a lot harder than regular c...
23923    What should you tell professionals when networ...
23924    What colleges universities degrees should I be...
23925    What is success and happiness    Tell me somet...
23926    What is a computer engineer   a computer progr...
23927    What major do I need to study to be a writer  ...
23928    Which careers are good if I enjoy working with...
23929    How can going to college help me advance my ca...
23930    Is age a factor for hiring entry level compute...
Name: questions_full_text, Length: 23931, dtype: object

## Tag부터 feature 추출하여 정리

In [12]:
students_tags = tag_users[tag_users['tag_users_user_id'].isin(students['students_id'])]
students_tags = pd.merge(students_tags, tags, left_on='tag_users_tag_id', right_on='tags_tag_id')
students_tags['user_type'] = 'student'

professionals_tags = tag_users[tag_users['tag_users_user_id'].isin(professionals['professionals_id'])]
professionals_tags = pd.merge(professionals_tags, tags, left_on='tag_users_tag_id', right_on='tags_tag_id')
professionals_tags['user_type'] = 'professional'

questions_tags = tag_questions
questions_tags = pd.merge(questions_tags, tags, left_on='tag_questions_tag_id', right_on='tags_tag_id')
questions_tags['user_type'] = 'question'

In [13]:
plt_data = pd.concat([students_tags, professionals_tags, questions_tags])
plt_data

C:\Users\chocolet\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

,tag_questions_question_id,tag_questions_tag_id,tag_users_tag_id,tag_users_user_id,tags_tag_id,tags_tag_name,user_type
0,NaN,NaN,8593.0,82cc74c0e18347e4b68b219e250eb10f,8593,scientist,student
1,NaN,NaN,8593.0,f3a5c976bec34f4289aa58938a837300,8593,scientist,student
2,NaN,NaN,8593.0,b3e73d394b19488b9c9ec13fcd7c43a7,8593,scientist,student
3,NaN,NaN,8593.0,59da5285144044c8a883fa9a6d40cd6a,8593,scientist,student
4,NaN,NaN,8593.0,d957ed2aac584dd79e3280ff679e818b,8593,scientist,student
5,NaN,NaN,8593.0,16aeb0575d3746998bb006a723bd9d6c,8593,scientist,student
6,NaN,NaN,8593.0,c5a741b700674a01b4248e3c34e96e94,8593,scientist,student
7,NaN,NaN,8593.0,91d97640f72a4e218d07e4ee2c5bcc78,8593,scientist,student
8,NaN,NaN,8593.0,e35ee83e3b174f1eaa6b6234b0d1b074,8593,scientist,student
9,NaN,NaN,8593.0,420088aa3fa14a82a2f89e2f481dd0b2,8593,scientist,student
10,NaN,NaN,8593.0,a624bc237424478db19a0aedda4d0c0e,8593,scientist,student
11,NaN,NaN,8593.0,70f6d80f027a4edb83caff73270466ea,8593,scientist,student
12,NaN,NaN,8593.0,cda0df547ff14b2fb74675e9fab4fdb1,8593,scientist,student
13,NaN,NaN,8593.0,47b20ac30907494d9f8c8f826b749ee2,8593,scientist,student
14,NaN,NaN,8593.0,46ba961b291e43dca64c1fed94538513,8593,scientist,student
15,NaN,NaN,8593.0,f8fc63244b6b42b684d50598a1c501dc,8593,scientist,student
16,NaN,NaN,8593.0,72477b4990204ac0a73f6deb0c70b301,8593,scientist,student
17,NaN,NaN,8593.0,01633de002284698a5430fd5d5f93810,8593,scientist,student
18,NaN,NaN,8593.0,c7b8513d2f1d480e862979d17a847122,8593,scientist,student
19,NaN,NaN,8593.0,d460799501e94656870e60d40039f5e7,8593,scientist,student
20,NaN,NaN,8593.0,1675057a0b834e52ac0169aa8e3c7b3f,8593,scientist,student
21,NaN,NaN,11460.0,d68c9bc7d1a841dc95164ced387275e0,11460,veterinary-medicine,student
22,NaN,NaN,11460.0,8cba49f40ce24cc883094d063e76d97b,11460,veterinary-medicine,student
23,NaN,NaN,11460.0,726bbceac5ca4f338ea0e623f5bb00a2,11460,veterinary-medicine,student
24,NaN,NaN,11460.0,02243609aad64e419312a3ddd4e98b52,11460,veterinary-medicine,student
25,NaN,NaN,11460.0,e46183f32b894cb3b38eaf48264f90dc,11460,veterinary-medicine,student
26,NaN,NaN,11460.0,07d604edcf294306adb3185c708a7e94,11460,veterinary-medicine,student
27,NaN,NaN,11460.0,ab487d83e3dd40eaa684b1e049d76d9d,11460,veterinary-medicine,student
28,NaN,NaN,11460.0,e2a59cd88e6f4d559c3418db5263dc36,11460,veterinary-medicine,student
29,NaN,NaN,11460.0,33e3f34d452948acbb5a23e59cc4a0b9,11460,veterinary-medicine,student
...,...,...,...,...,...,...,...
76523,fbebebcd89be47649b3d0794f3cafb00,39091.0,NaN,NaN,39091,aviationuniversities,question
76524,8f91cc939c2c456386c7189839012b55,39092.0,NaN,NaN,39092,aircraftmaintenace,question
76525,6725b02443e44b3e8dca5fcf842f74ec,39092.0,NaN,NaN,39092,aircraftmaintenace,question
76526,fbebebcd89be47649b3d0794f3cafb00,39092.0,NaN,NaN,39092,aircraftmaintenace,question
76527,fbebebcd89be47649b3d0794f3cafb00,39093.0,NaN,NaN,39093,cheifengineer,question
76528,6725b02443e44b3e8dca5fcf842f74ec,39094.0,NaN,NaN,39094,licenceengineer,question
76529,6725b02443e44b3e8dca5fcf842f74ec,39095.0,NaN,NaN,39095,propulsion,question
76530,6725b02443e44b3e8dca5fcf842f74ec,39096.0,NaN,NaN,39096,aerospaceuniversity,question
76531,6725b02443e44b3e8dca5fcf842f74ec,39097.0,NaN,NaN,39097,enginesandpowerplant,question
76532,598bea9108ca4775ba730b0e6a567929,39098.0,NaN,NaN,39098,aviationprofessor,question
76533,598bea9108ca4775ba730b0e6a567929,39099.0,NaN,NaN,39099,airworthness,question
76534,55c249da38c648188e342f057cb71822,39100.0,NaN,NaN,39100,airbus,question
76535,55c249da38c648188e342f057cb71822,39101.0,NaN,NaN,39101,kingstonuniversity,question
76536,55c249da38c648188e342f057cb71822,39102.0,NaN,NaN,39102,geaviation,question
76537,55c249da38c648188e342f057cb71822,39103.0,NaN,NaN,39103,aerospacecompany,question
76538,8f91cc939c2c456386c7189839012b55,39104.0,NaN,NaN,39104,aerospacegraduates,question
76539,3a88b3fa2d2e48d489728298c985b076,39109.0,NaN,NaN,39109,familyvlogs,question
76540,3a88b3fa2d2e48d489728298c985b076,39110.0,NaN,NaN,39110,funvlogs,question
76541,606dbdca5def439aa3eb59258ae7f5b9,39141.0,NaN,NaN,39141,jobrequirements,question
76542,dc33139503744d1fafdf41a0b2b8e321,39142.0,NaN,NaN,39142,auto-motive,question
76543,3871d39fd1654b1c9b8fc6a66dcdf5cd,39165.0,NaN,NaN,39165,refrigeration,question
76544,a25c4cee64974799ba0c150e6afce95f,39182.0,NaN,NaN,39182,raptor,question
76545,c7cb6c54dbb34c0ab2eb23751deea6ad,39183.0,NaN,NaN,39183,austria,question
76546,f4790c8029064b41bd410f66c5039890,39183.0,NaN,NaN,39183,austria,question
76547,e8c8ed32802b4090b5865dd3c2c3f42a,39183.0,NaN,NaN,39183,austria,question
76548,72affe86909d49c09761a1d376476c92,39183.0,NaN,NaN,39183,austria,question
76549,5b86153f2b6c46a4801bb39e10e01281,39248.0,NaN,NaN,39248,weldernation,question
76550,0946a81d511b48c58376fd59058d3b12,39249.0,NaN,NaN,39249,welder,question
76551,b4de8ccfcd874481bfc80ceacb0caac8,39249.0,NaN,NaN,39249,welder,question
76552,0946a81d511b48c58376fd59058d3b12,39250.0,NaN,NaN,39250,nation,question

In [14]:
from nltk.stem import WordNetLemmatizer
import nltk
import string

remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)
lemmar = WordNetLemmatizer()

def LemTokens(tokens):
    return [lemmar.lemmatize(token) for token in tokens]

def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

In [18]:
students_tags['tags_tag_name']

0                         scientist
1                         scientist
2                         scientist
3                         scientist
4                         scientist
5                         scientist
6                         scientist
7                         scientist
8                         scientist
9                         scientist
10                        scientist
11                        scientist
12                        scientist
13                        scientist
14                        scientist
15                        scientist
16                        scientist
17                        scientist
18                        scientist
19                        scientist
20                        scientist
21              veterinary-medicine
22              veterinary-medicine
23              veterinary-medicine
24              veterinary-medicine
25              veterinary-medicine
26              veterinary-medicine
27              veterinary-medicine
28              veterinary-medicine
29              veterinary-medicine
                    ...
19175                     #medicine
19176                      #biology
19177                      #science
19178                         horse
19179                   horseriding
19180         horseridinginstructor
19181                  horsetrainer
19182                       bigdata
19183                    adirondack
19184         computational-biology
19185        mechanicalengineeering
19186       mechanical-engineeering
19187            medical-technology
19188              pure-mathematics
19189                 combinatorics
19190                  discretemath
19191                 mooddisorders
19192               eatingdisorders
19193                   weatherjobs
19194                    #latinidad
19195                      selflove
19196                publicspeaking
19197               #businessschool
19198            #careerimprovement
19199                #communication
19200    #howtogetinsidetheindustry
19201                      #masters
19202                 aplacetostart
19203                     electrian
19204                womens-studies
Name: tags_tag_name, Length: 19205, dtype: object

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english' , \
                             ngram_range=(1,2), min_df=0.005, max_df=0.95 )

#tags_tag_name 컬럼값으로 feature vectorization 수행
feature_vect = tfidf_vect.fit_transform(students_tags['tags_tag_name'])

C:\Users\chocolet\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:300: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  'stop_words.' % sorted(inconsistent))

In [19]:
from sklearn.cluster import KMeans

# 15개 집합으로 군집화 수행. 예제를 위해 동일한 클러스터링 결과 도출용 random_state=0 
km_cluster = KMeans(n_clusters=24,max_iter=10000, random_state=0)
km_cluster.fit(feature_vect)
cluster_label = km_cluster.labels_
cluster_centers = km_cluster.cluster_centers_

In [20]:
students_tags['cluster_label'] = cluster_label
s_t_c=students_tags[students_tags['cluster_label'] ==0]

In [21]:
students_tags[students_tags['cluster_label'] ==9]

,tag_users_tag_id,tag_users_user_id,tags_tag_id,tags_tag_name,user_type,cluster_label
7556,11560,12594f3eb0404e25a320376e98309618,11560,professionals,student,9
7557,11560,aa7d73fa706f4994ae0c266ca5f7c861,11560,professionals,student,9
7558,11560,b5dd08306dba4380952a83e5dad5f4e4,11560,professionals,student,9
7559,11560,6d0fbb6bdf004a7289b87c6436b7a477,11560,professionals,student,9
7560,11560,89ab75f30fd944faad08ccc14f28e664,11560,professionals,student,9
7561,11560,68b57c9b076042e6be5780f0fdd0ee22,11560,professionals,student,9
7562,11560,f48be4dc84684941b9ae5221bf2eac1f,11560,professionals,student,9
7563,11560,06c0925364ab4c378bfd776172d8f219,11560,professionals,student,9
10982,5648,9665256d2d624660980be14136ac1c88,5648,professional,student,9
10983,5648,9e0c00a262384d7cb9ce96c19e9aa803,5648,professional,student,9
10984,5648,39088c79426c4c7b96d9668841a2aa3a,5648,professional,student,9
10985,5648,f8b4055e4e1740b0b887e8294096e727,5648,professional,student,9
10986,5648,6a5dca4144124f0a9bc9339d5d5ac555,5648,professional,student,9
10987,5648,c626f443cd374a6dbab348aa0bdb1b25,5648,professional,student,9
10988,5648,94b07e0f6bea4ae4b55473717a60c8df,5648,professional,student,9
10989,5648,2fff68e8942a4c3fbca79dadd6c7eeab,5648,professional,student,9
10990,5648,e5742dd2a26942d3b18cc9a71fbf477e,5648,professional,student,9
10991,5648,1cbd28060ad442ffa71917e2fad1b1b6,5648,professional,student,9
10992,5648,1fc72713efdb45db801ff48ce29b9ad8,5648,professional,student,9
10993,5648,e7496b95b08e429d9fd976e06493c8de,5648,professional,student,9
10994,5648,50acf600f3684c5aadf572bc96753175,5648,professional,student,9
10995,5648,c8c6e9e580484e14a25d36d126b0e89b,5648,professional,student,9
10996,5648,65b7c133f2374f24a1ba2f803d53ad1b,5648,professional,student,9
10997,5648,b4c9c60bfe194421a59d6013f3541af6,5648,professional,student,9
10998,5648,0fad8b57dfc7419699cbc6864d69868f,5648,professional,student,9
10999,5648,379ecfbba4854502b24f06efaa08d58e,5648,professional,student,9
11000,5648,c87e3025ae28458db8bbfb15329f1147,5648,professional,student,9
11001,5648,fc87191dd87048a7b487ba02b5d8113f,5648,professional,student,9
11002,5648,c1de624f305f4e309649fb49d0246a5a,5648,professional,student,9
11003,5648,aae289570be7488c910d56e3eac43e29,5648,professional,student,9
...,...,...,...,...,...,...
11120,5648,91d5fb5eea724c73972be5e46e2e317b,5648,professional,student,9
11121,5648,a2f6730d1078415081f99241e6a02d4a,5648,professional,student,9
11122,5648,7bc366d1b672416b8b5cd5dc169f9c36,5648,professional,student,9
11123,5648,19b066bc7c9a44debb5609b4330eca12,5648,professional,student,9
11124,5648,8fdd585ca373429d9f4a57669a012d31,5648,professional,student,9
11125,5648,44f757ad855d4bff929c32ea6e122621,5648,professional,student,9
11126,5648,d859f0c8ee3541349cb79f3f593f7030,5648,professional,student,9
11127,5648,f24069958a9c4f5591d0c05694dbef16,5648,professional,student,9
11128,5648,6ce9c304246245dc871d2331fd959fe8,5648,professional,student,9
11129,5648,be09d16c1780435dafa970d8bf433199,5648,professional,student,9
11130,5648,55cd05e9faf3448d847433bc66c0979d,5648,professional,student,9
11131,5648,3ce65102c42d41588d8b24b5a376a41b,5648,professional,student,9
11132,5648,653469c581b0404a9f045de9bd6f5cf7,5648,professional,student,9
11133,5648,e3af0929e6494b7cbac08a25844a4b95,5648,professional,student,9
11134,5648,f59bf6d6b2d54ab68d67bb26b0aedb16,5648,professional,student,9
11135,5648,af945d138db841eba81f3383c3b3f8b8,5648,professional,student,9
11136,5648,67093d97962f4fc2900db0c9adaa242b,5648,professional,student,9
11137,5648,3163866e3bdb4dad87fd9428fe6839e8,5648,professional,student,9
11138,5648,617e8c5bfd5540bbbcbcca28578fe684,5648,professional,student,9
11139,5648,31c8d9e8731042a68bff8685daf67022,5648,professional,student,9
11140,5648,4c0cb99eca344b0f944c1aff42f6239e,5648,professional,student,9
11141,5648,b5d8f8d8507a4bd5928ddaf8a532db34,5648,professional,student,9
11142,5648,230b4a3b592a4f499f9109c827d9b79e,5648,professional,student,9
11143,5648,cecf348b56324880ab659aa52300b4a8,5648,professional,student,9
11144,5648,77c6c66d3c4f4c1a892cbb0528da6d45,5648,professional,student,9
11145,5648,5fb331ddd7a54f9fa96be438d70f9407,5648,professional,student,9
11146,5648,603e0a6210014d9a96ba5a549a81ada0,5648,professional,student,9
11147,5648,f632691097ee483dbbc7d6cbef538006,5648,professional,student,9
11148,5648,9fba3f7082d2433e87125567e89fed9d,5648,professional,student,9
11149,5648,eb2b5b36876b4658b302e345eb25c356,5648,professional,student,9

In [22]:
students_tags[students_tags['tags_tag_name']=='professors']

,tag_users_tag_id,tag_users_user_id,tags_tag_id,tags_tag_name,user_type,cluster_label
7331,27297,5dd43a6bfae147dcb530850bcca6c810,27297,professors,student,0
7332,27297,f2c179a563024ccc927399ce529094b5,27297,professors,student,0
7333,27297,7031407898544fc1b7603d9678a44f93,27297,professors,student,0
7334,27297,fb89466890f44176a8bf9d3595158ba0,27297,professors,student,0
7335,27297,967120f54bc64996bcf28848f6b55c95,27297,professors,student,0
7336,27297,7b6ab17eba0e48ffa5eab19e387459fb,27297,professors,student,0
7337,27297,460c257ad98446ec9d4cadaab40dcbf4,27297,professors,student,0
7338,27297,19aacb1990d545a686a9f45de44dbcce,27297,professors,student,0
7339,27297,f28355582fe54c138d0f64771171c8f4,27297,professors,student,0
7340,27297,1d5371ae68bf4399816d7c3513f683f3,27297,professors,student,0
7341,27297,c792812d3f6d4c559c632ee8ee6d7976,27297,professors,student,0
7342,27297,1cfb7379fee54285b7d1125d512d7acc,27297,professors,student,0
7343,27297,6306b6fff51e4470891e554de710e40b,27297,professors,student,0
7344,27297,4df56458b863437faceb06de7828fd39,27297,professors,student,0
7345,27297,ba6b143a5d1e4be99840b4443404e3d2,27297,professors,student,0
7346,27297,89ab75f30fd944faad08ccc14f28e664,27297,professors,student,0
7347,27297,61a3c2e576b045f78043e6a113aa52d0,27297,professors,student,0
7348,27297,406bc2ff419547f7a6f6669f097a6691,27297,professors,student,0
7349,27297,eb2b5b36876b4658b302e345eb25c356,27297,professors,student,0

In [23]:
tfidf_vect2 = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english' , \
                             ngram_range=(1,2), min_df=0.005, max_df=0.95 )

#tags_tag_name 컬럼값으로 feature vectorization 수행
feature_vect2 = tfidf_vect2.fit_transform(s_t_c['tags_tag_name'])

C:\Users\chocolet\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:300: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  'stop_words.' % sorted(inconsistent))

In [24]:
km_cluster2 = KMeans(n_clusters=7,max_iter=10000, random_state=0)
km_cluster2.fit(feature_vect2)
cluster_label2 = km_cluster2.labels_
cluster_centers2 = km_cluster2.cluster_centers_

In [25]:
s_t_c=s_t_c.drop('cluster_label', axis=1)

In [44]:
s_t_c[s_t_c['cluster_label'] ==1]

,tag_users_tag_id,tag_users_user_id,tags_tag_id,tags_tag_name,user_type,cluster_label
8662,187,f56d20956363407db018f8ef36ad5bea,187,jobs,student,1
8663,187,0b71d5c10a5544ad8b50bf7d6bda9fb8,187,jobs,student,1
8664,187,056ff80fe5d64123bb0e07ef20a6fee3,187,jobs,student,1
8665,187,f2c179a563024ccc927399ce529094b5,187,jobs,student,1
8666,187,23386e0176054ae192484ff8a05c9f98,187,jobs,student,1
8667,187,45327e44a7534911af88cf4da17593c3,187,jobs,student,1
8668,187,4267329a2f2f45889ab8ffb9632ebe2d,187,jobs,student,1
8669,187,def7c9ce29b1473cb4ecbf111fbc6b58,187,jobs,student,1
8670,187,4b606a46a419471287bb5867dd3c3a0f,187,jobs,student,1
8671,187,87ec9311edda4585bb9fb22aa5bdf7f1,187,jobs,student,1
8672,187,47d6dcb460224ba0a97239c89c91cc7c,187,jobs,student,1
8673,187,cb1338a3e8504f6baf3a53fd616ce013,187,jobs,student,1
8674,187,b3bc740ed50849f1bb58afc0860106d4,187,jobs,student,1
8675,187,c150b17d9781443f9794197547116c73,187,jobs,student,1
8676,187,437a81f330e24abaaa0621045dcc4f40,187,jobs,student,1
8677,187,24f1a2d031f24e1f938f865d85e36e76,187,jobs,student,1
8678,187,3a20e626d7f84177acff326b7e1d975b,187,jobs,student,1
8679,187,bd979fa48ebb466a83e1a41967afb5b9,187,jobs,student,1
8680,187,b688212f77ef4abf9b245d50336740ef,187,jobs,student,1
8681,187,93a6e5aaee534a88a7247314f7e4804b,187,jobs,student,1
8682,187,bdaf014618c2460cbbf872b101cf1029,187,jobs,student,1
8683,187,7d23247a0ecb44dd88f2dbc957f97e76,187,jobs,student,1
8684,187,fb8595b557544fb1b9215728d8e09963,187,jobs,student,1
8685,187,cdc0f29f9f8f42cdb9f2b71d06654e18,187,jobs,student,1
8686,187,2afd57e38c234cd1871cb0032ff5a0f7,187,jobs,student,1
8687,187,eba788f5b16242ca81f6771d0de22f60,187,jobs,student,1
8688,187,cf0762161ce74ca085f9e16fb854dc09,187,jobs,student,1
8689,187,4897c17a0169408faf1379b86ff32b6a,187,jobs,student,1
8690,187,02d26f461517482da1da0d96d40c57bb,187,jobs,student,1
8691,187,80fb2e0968ac4b0ea3bf2b2290ee89c9,187,jobs,student,1
...,...,...,...,...,...,...
9927,27333,c0748697f70d4a75bfa7142ba4738afa,27333,job,student,1
9928,27333,ec6aca1d70834826b7113a2c1267c01f,27333,job,student,1
9929,27333,d2e2ee6686684902b76779c64564118c,27333,job,student,1
9930,27333,57778f7241a341599f4c2010832e3c8d,27333,job,student,1
9931,27333,93806dec56514001b4b585b8d74ee0f4,27333,job,student,1
9932,27333,b4656e510759496fb570b582b803a54e,27333,job,student,1
9933,27333,9cb1e54e648b4f9e8983be10313b54e4,27333,job,student,1
9934,27333,b0b96aa94faa460f8513ac8e6dcaa927,27333,job,student,1
9935,27333,eb3358d54e5e452288fd8ce57932ab7f,27333,job,student,1
9936,27333,a1b287cdd068497da8c915c198c562b6,27333,job,student,1
9937,27333,c2da26e91c8c47418103d63f3333ab68,27333,job,student,1
9938,27333,367ebd2ba8934fdcb92095eda7bf48c2,27333,job,student,1
9939,27333,2f5d9cbcff914fd4b20de382e53b8c26,27333,job,student,1
9940,27333,45852d7b04fd40a0b8e3d92c8a37aad0,27333,job,student,1
9941,27333,93fbe17a269f4904a38bc320a583ef1a,27333,job,student,1
9942,27333,b4af31bb44874eb0a3f010bcf09d4562,27333,job,student,1
9943,27333,3166f3f338dc4ab2ae7ace463878e5fd,27333,job,student,1
9944,27333,c4462098f25a467e88cfc849b288b8f9,27333,job,student,1
9945,27333,2f7bdb78b47f4b9d9c0cc31a6adf6ec3,27333,job,student,1
9946,27333,fc0c143500134ef79e0db0ad8b4b4cb3,27333,job,student,1
9947,27333,3c2a76f45158477d9d06e9e5d92ce471,27333,job,student,1
9948,27333,7397ce4f4fa941668340d9068d981f2c,27333,job,student,1
9949,27333,f4908e3f227444dc8c5c91a92d0e35a0,27333,job,student,1
9950,27333,be095af0060a47a8ba89b9e5d8ac7be5,27333,job,student,1
9951,27333,a852ab1cb63944729a780d436bb17586,27333,job,student,1
9952,27333,a796027f5c3d494488dc1185f92d3a38,27333,job,student,1
9953,27333,19f528d4917e45f5997b71e246ef82bd,27333,job,student,1
9954,27333,88cd681507b8410b8ca4a3c5c1d8bd03,27333,job,student,1
9955,27333,b56f7d4be3284a93b40129931556f56c,27333,job,student,1
9956,27333,f6361bef40324e7e8af069459f1ba6d1,27333,job,student,1

In [26]:
s_t_c['cluster_label'] = cluster_label2
s_t_c2=s_t_c[s_t_c['cluster_label'] ==0]

In [27]:
tfidf_vect3 = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english' , \
                             ngram_range=(1,2), min_df=0.005, max_df=0.95 )

#tags_tag_name 컬럼값으로 feature vectorization 수행
feature_vect3 = tfidf_vect3.fit_transform(s_t_c2['tags_tag_name'])

C:\Users\chocolet\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:300: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  'stop_words.' % sorted(inconsistent))

In [52]:
km_cluster3 = KMeans(n_clusters=3,max_iter=10000, random_state=0)
km_cluster3.fit(feature_vect3)
cluster_label3 = km_cluster3.labels_
cluster_centers3 = km_cluster3.cluster_centers_

In [53]:
s_t_c2['cluster_label'] = cluster_label3

C:\Users\chocolet\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [56]:
s_t_c3=s_t_c2[s_t_c2['cluster_label']==0]

In [59]:
tfidf_vect4 = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english' , \
                             ngram_range=(1,2), min_df=0.0005, max_df=0.955 )

#tags_tag_name 컬럼값으로 feature vectorization 수행
feature_vect4 = tfidf_vect4.fit_transform(s_t_c3['tags_tag_name'])

In [86]:
km_cluster4 = KMeans(n_clusters=15,max_iter=10000, random_state=0)
km_cluster4.fit(feature_vect4)
cluster_label4 = km_cluster4.labels_
cluster_centers4 = km_cluster4.cluster_centers_

In [89]:
s_t_c3['cluster_label'] = cluster_label4
s_t_c3[s_t_c3['cluster_label']==0]

C:\Users\chocolet\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,tag_users_tag_id,tag_users_user_id,tags_tag_id,tags_tag_name,user_type,cluster_label
3763,28830,a7f95f095d6547b1a31a274016204b2b,28830,photography,student,0
3764,28830,a7f95f095d6547b1a31a274016204b2b,28830,photography,student,0
3765,28830,1027121e74a84df4ae63113d1c0c84a2,28830,photography,student,0
3766,28830,e9cb188fa71545718f9ee4959b21c4ae,28830,photography,student,0
3767,28830,b7e0f8765c2a48a481f9bc00b9c801d3,28830,photography,student,0
3768,28830,727297b4432e496489424f019fa05481,28830,photography,student,0
3769,28830,c153d19a3fc946569d492b9eae7eeb5c,28830,photography,student,0
3770,28830,2d33f741c66240fd8ac1c15aeaefa0af,28830,photography,student,0
3771,28830,32b33a08cfd643709a9fa0953b916600,28830,photography,student,0
3772,28830,0912765ee37c4bf7b1f3bf551c642f96,28830,photography,student,0
3773,28830,b26c92aaa17344aaa54f630666a902e7,28830,photography,student,0
3774,28830,7f9fe2aaa9ac4d989c3c845eda5e306f,28830,photography,student,0
3775,28830,d2f6f83d68104bc1b8216f49e5c242ea,28830,photography,student,0
3776,28830,5b7ff7960a0746cf8517256f69e1dab1,28830,photography,student,0
3777,28830,29bb0d1d33754974a9e16c30e90bb358,28830,photography,student,0
3778,28830,497dc3ebdace45ad955aff56ff06a01c,28830,photography,student,0
3779,28830,1403165512754e7ead4fb245accbcef7,28830,photography,student,0
3780,28830,a1c9b64b9e444215bd2b998e5be46e7d,28830,photography,student,0
3781,28830,bc75ac7be9244e50ac93967bc03537dd,28830,photography,student,0
3782,28830,5c1f8ebf037643f284f751330eed792a,28830,photography,student,0
3783,28830,4cb5ae9edb23433d891eb529520a7781,28830,photography,student,0
3784,28830,da7749129e714ad6970be4951fb0c4d9,28830,photography,student,0
3785,28830,2a32d8134ebd4440b0ba6bdfb4b6ba63,28830,photography,student,0
3786,28830,8afef8b1f7c64b6fad91a15ec973c3fb,28830,photography,student,0
3787,28830,6c893d393d5849489c4b7af041a1fdfd,28830,photography,student,0
3788,28830,2871b423f7e342ee8c1d3f27ff954db3,28830,photography,student,0
3789,28830,1c2cab19b98e4de6a02dfdb2cee03b5d,28830,photography,student,0
3790,28830,fd344e3272894abc85e7eb4f68452fbc,28830,photography,student,0
3791,28830,830aa1ec8cef450f924241f8e929a383,28830,photography,student,0
3792,28830,730059fbc9a74701b932154cd206b325,28830,photography,student,0
...,...,...,...,...,...,...
3799,28830,3bd8f2a6c37f4871ac601c434c420b22,28830,photography,student,0
3800,28830,93396a0bb1d9432fb51ecb3bb5d81560,28830,photography,student,0
3801,28830,57184f3b6e23484595a521d0fa9197ac,28830,photography,student,0
3802,28830,8eb9614041d84202a6d5e87ad1c689a0,28830,photography,student,0
3803,28830,f7e0f6dbf15e44d69c941d6916e7450e,28830,photography,student,0
3804,28830,2c6d9fa879be4a58b07ae620748ceca5,28830,photography,student,0
3805,28830,8ca03059f6c44ebd80385d6560cd940f,28830,photography,student,0
3806,28830,22e0674fa5214fe891d8a2e0cabf1738,28830,photography,student,0
3807,28830,5a400f2fe9a24772b163823fd8d6b571,28830,photography,student,0
3808,28830,514e999d35df41b1be150b5ed859c367,28830,photography,student,0
3809,28830,42e395e204c040159fb6171dc10c39a5,28830,photography,student,0
3810,28830,1fb16726e3a14e93aefde4c21a3129c8,28830,photography,student,0
3811,28830,dcdb2a338a5e4ef7b203aada86d1edac,28830,photography,student,0
3812,28830,66d54cc26d7f43ceb30e1909277d5b99,28830,photography,student,0
3813,28830,615217e048514d47840c808aa3f78ff1,28830,photography,student,0
3814,28830,bc4d1b8be6884843bbca6876a3c6044e,28830,photography,student,0
3815,28830,4bf474cb8fa04b8f916e6c2af71350b9,28830,photography,student,0
3816,28830,1d83f8d116864345b44d5a3073810818,28830,photography,student,0
3817,28830,8fe7924868ab4dadb57f8dff18d0f11a,28830,photography,student,0
3818,28830,8344fef05f534f6c835372b75c500207,28830,photography,student,0
3819,28830,13c8c0f651e34106b00f0156f6263fa7,28830,photography,student,0
3820,28830,73c1822132594854b7190a1bdd0ecd24,28830,photography,student,0
3821,28830,ebed8f0c00044817a19b109daa222d89,28830,photography,student,0
3822,28830,c4a0e577c53e469f8b6871af1dac7e5a,28830,photography,student,0
3823,28830,c87c389933a140de85829f5baa16db3d,28830,photography,student,0
3824,28830,3dff8b1a4602468eac610c70be8fb6d9,28830,photography,student,0
3825,28830,5d6875960de14fdea7af0ad5637ff386,28830,photography,student,0
3826,28830,ed69d8e1e3b84aedb1334d68e591ff98,28830,photography,student,0
3827,28830,8476c90a9e8e429d972502cb71c7ab4b,28830,photography,student,0
17792,31865,bbbd0f43130b4364b8aa9a09606aa976,31865,photography-,student,0